/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description 登录成功
*/
export type PostAuthLogin200 = {
    /**
     * @type string | undefined
    */
    token?: string | undefined;
    /**
     * @type object | undefined
    */
    user?: {
        /**
         * @type integer | undefined
        */
        id?: number | undefined;
        /**
         * @type string | undefined
        */
        name?: string | undefined;
    } | undefined;
};

export type PostAuthLoginMutationRequest = {
    /**
     * @type string
    */
    username: string;
    /**
     * @type string
    */
    password: string;
};

export type PostAuthLoginMutationResponse = PostAuthLogin200;

export type PostAuthLoginMutation = {
    Response: PostAuthLogin200;
    Request: PostAuthLoginMutationRequest;
    Errors: any;
};