/* eslint-disable no-alert, no-console */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const operations = {
  "post_auth-login": {
    "path": "/auth/login",
    "method": "post"
  },
  "get_users-id": {
    "path": "/users/:id",
    "method": "get"
  }
}