/* eslint-disable no-alert, no-console */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { GetUsersIdQueryResponse, GetUsersIdPathParams } from "../../../types/UserController/GetUsersId.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";

function getGetUsersIdUrlClient({ id }: { id: GetUsersIdPathParams["id"] }) {
  const res = { method: 'GET', url: `/users/${id}` as const }  
  return res
}

/**
 * @summary 获取用户信息
 * {@link /users/:id}
 */
export async function getUsersIdClient({ id }: { id: GetUsersIdPathParams["id"] }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetUsersIdQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetUsersIdUrlClient({ id }).url.toString(), ... requestConfig })  
  return res
}