/* eslint-disable no-alert, no-console */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { postAuthLoginClient } from "./postAuthLoginClient.ts";

export function authService() {
  return { postAuthLoginClient }
}