/* eslint-disable no-alert, no-console */
/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { PostAuthLoginMutationRequest, PostAuthLoginMutationResponse } from "../../../types/AuthController/PostAuthLogin.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";

function getPostAuthLoginUrlClient() {
  const res = { method: 'POST', url: `/auth/login` as const }  
  return res
}

/**
 * @summary 用户登录
 * {@link /auth/login}
 */
export async function postAuthLoginClient(data: PostAuthLoginMutationRequest, config: Partial<RequestConfig<PostAuthLoginMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostAuthLoginMutationResponse, ResponseErrorConfig<Error>, PostAuthLoginMutationRequest>({ method : "POST", url : getPostAuthLoginUrlClient().url.toString(), data : requestData, ... requestConfig })  
  return res
}