/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { User } from "../User.ts";

export type GetUsersIdPathParams = {
    /**
     * @type integer
    */
    id: number;
};

/**
 * @description 用户详情
*/
export type GetUsersId200 = User;

export type GetUsersIdQueryResponse = GetUsersId200;

export type GetUsersIdQuery = {
    Response: GetUsersId200;
    PathParams: GetUsersIdPathParams;
    Errors: any;
};