/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type User = {
    /**
     * @type integer | undefined
    */
    id?: number | undefined;
    /**
     * @type string | undefined
    */
    name?: string | undefined;
    /**
     * @type string | undefined
    */
    email?: string | undefined;
};